/* Filename: timestamp.h       */
/* generated by nerd_timestamp */

/* product string descriptor */
const uchar string_prod[] = {
	66, 0x03,
	'n',0, 'e',0, 'r',0, 'd',0, ' ',0, '-',0, ' ',0, 'b',0, 'u',0, 'i',0,
	'l',0, 't',0, ':',0, 
	'2',0, '0',0, '0',0, '6',0, '.',0, '0',0, '6',0, '.',0, '2',0, '4',0,
	' ',0, '0',0, '0',0, ':',0, '5',0, '5',0, ':',0, '4',0, '9',0
};

